[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment for static site
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy for game security
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; canvas-src 'self';"

[[headers]]
  # Cache static assets for performance
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache CSS files
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache HTML with shorter duration for updates
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Specific headers for the main game file
  for = "/index.html"
  [headers.values]
    # Enable features needed for the game
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    # Educational content metadata
    X-Robots-Tag = "index, follow"

[[redirects]]
  # Redirect any 404 to the main game (single page app behavior)
  from = "/*"
  to = "/index.html"
  status = 404

[[redirects]]
  # Redirect root variants to main game
  from = "/game"
  to = "/index.html"
  status = 301

[[redirects]]
  # Legacy redirect for old server.py access patterns
  from = "/server.py"
  to = "/index.html"
  status = 301

# Deploy settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# Form handling (if needed for future feedback forms)
[build.processing.images]
  compress = true